"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

import os
from pathlib import Path
from urllib.parse import quote_plus
from dotenv import load_dotenv  # 1. Додай цей імпорт

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')  # 2. Це змусить Python прочитати твій файл

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'unsafe-dev-secret-key')
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if host.strip()
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'accounts',
    'workforce',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

supabase_host = os.getenv('SUPABASE_DB_HOST')
supabase_password = os.getenv('SUPABASE_DB_PASSWORD')
supabase_user = os.getenv('SUPABASE_DB_USER', 'postgres')
supabase_db = os.getenv('SUPABASE_DB_NAME', 'postgres')
supabase_port = os.getenv('SUPABASE_DB_PORT', '5432')

supabase_db_url = None
if supabase_host and supabase_password:
    supabase_db_url = (
        f'postgresql://{supabase_user}:{quote_plus(supabase_password)}'
        f'@{supabase_host}:{supabase_port}/{supabase_db}'
    )

database_url = os.getenv('DATABASE_URL')
allow_sqlite_fallback = os.getenv('ALLOW_SQLITE_FALLBACK', 'False').lower() == 'true'
if not database_url:
    if allow_sqlite_fallback:
        database_url = f'sqlite:///{BASE_DIR / "db.sqlite3"}'
    else:
        raise ImproperlyConfigured(
            'Database is not configured. Set DATABASE_URL (recommended for Supabase) '
            'or SUPABASE_DB_HOST + SUPABASE_DB_PASSWORD. '
            'If you really want local SQLite, set ALLOW_SQLITE_FALLBACK=True.'
        )

DATABASES = {
    'default': dj_database_url.parse(
        database_url,
        conn_max_age=int(os.getenv('DB_CONN_MAX_AGE', '600')),
        ssl_require=database_url.startswith('postgresql://'),
    )
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = os.getenv('TIME_ZONE', 'Europe/Kyiv')
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')
    if origin.strip()
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}
