# Generated by Django 5.2.13 on 2026-04-22 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workforce", "0002_client_project_subscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("plaid", "Plaid"),
                            ("salt-edge", "Salt Edge"),
                            ("mono", "Mono"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                ("encrypted_token", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("error", "Error"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_secret", models.CharField(blank=True, max_length=255)),
                ("external_client_id", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_account_id", models.CharField(max_length=128)),
                ("iban_masked_pan", models.CharField(blank=True, max_length=64)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("checking", "Checking"),
                            ("savings", "Savings"),
                            ("credit", "Credit"),
                            ("loan", "Loan"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("is_tracked", models.BooleanField(default=True)),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="workforce.bankconnection",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_tx_id", models.CharField(max_length=128)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "In"), ("out", "Out")], max_length=3
                    ),
                ),
                ("mcc", models.CharField(blank=True, max_length=8)),
                ("description", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField()),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="workforce.bankaccount",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                fields=("connection", "external_account_id"),
                name="uniq_bank_account_per_connection_external_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransaction",
            constraint=models.UniqueConstraint(
                fields=("account", "external_tx_id"),
                name="uniq_bank_tx_per_account_external_id",
            ),
        ),
    ]
