# Generated by Django 6.0.4 on 2026-04-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_client_project_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('monobank', 'Monobank'), ('privat24', 'Privat24'), ('wise', 'Wise'), ('revolut', 'Revolut')], max_length=32)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('error', 'Error'), ('syncing', 'Syncing'), ('disabled', 'Disabled')], default='connected', max_length=20)),
                ('encrypted_token', models.TextField()),
                ('token_masked', models.CharField(max_length=128)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('disabled_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('monobank', 'Monobank')], default='monobank', max_length=32)),
                ('external_account_id', models.CharField(max_length=128)),
                ('iban', models.CharField(blank=True, max_length=64)),
                ('masked_pan', models.CharField(blank=True, max_length=32)),
                ('holder', models.CharField(blank=True, max_length=150)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sync_cursor', models.BigIntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_tx_id', models.CharField(max_length=128, unique=True)),
                ('occurred_at', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('mcc', models.PositiveIntegerField(blank=True, null=True)),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('category', models.CharField(default='uncategorized', max_length=64)),
                ('category_source', models.CharField(default='auto', max_length=32)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='workforce.bankaccount')),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='bankconnection',
            constraint=models.UniqueConstraint(fields=('created_by', 'provider'), name='uniq_bank_connection_provider_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'external_account_id', 'created_by'), name='uniq_bank_account_provider_external_owner'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account', 'occurred_at'], name='workforce_ba_bank_ac_35b5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['category'], name='workforce_ba_categor_2817ee_idx'),
        ),
    ]
