# Generated by Django 6.0.4 on 2026-04-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_client_project_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('monobank', 'Monobank'), ('privat24', 'Privat24'), ('wise', 'Wise'), ('revolut', 'Revolut')], max_length=32)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('error', 'Error'), ('syncing', 'Syncing'), ('disabled', 'Disabled')], default='connected', max_length=20)),
                ('encrypted_token', models.TextField()),
                ('token_masked', models.CharField(max_length=128)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('disabled_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='bankconnection',
            constraint=models.UniqueConstraint(fields=('created_by', 'provider'), name='uniq_bank_connection_provider_per_owner'),
        ),
    ]
