# Generated by Django 6.0.4 on 2026-04-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_client_project_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonobankIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Monobank', max_length=120)),
                ('token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monobank_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='MonobankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100)),
                ('iban', models.CharField(blank=True, max_length=64)),
                ('currency_code', models.IntegerField()),
                ('balance', models.BigIntegerField(default=0)),
                ('cashback_type', models.CharField(blank=True, max_length=32)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('masked_pan', models.JSONField(blank=True, default=list)),
                ('is_tracking_enabled', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='workforce.monobankintegration')),
            ],
            options={
                'ordering': ('account_id',),
            },
        ),
        migrations.CreateModel(
            name='MonobankOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(max_length=180)),
                ('operation_time', models.DateTimeField()),
                ('amount', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('mcc', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='workforce.monobankaccount')),
            ],
            options={
                'ordering': ('-operation_time',),
            },
        ),
        migrations.AddConstraint(
            model_name='monobankaccount',
            constraint=models.UniqueConstraint(fields=('integration', 'account_id'), name='uniq_monobank_account_per_integration'),
        ),
        migrations.AddConstraint(
            model_name='monobankoperation',
            constraint=models.UniqueConstraint(fields=('account', 'operation_id'), name='uniq_monobank_operation_per_account'),
        ),
    ]
