# Generated by Django 6.0.4 on 2026-04-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0007_bankaccount_masked_pan_len'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_cash_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual cash balance',
                'verbose_name_plural': 'Manual cash balances',
            },
        ),
    ]
